export type CategorySlug =
  | "broast-special"
  | "burgers"
  | "wraps"
  | "pizza"
  | "fries"
  | "combos"
  | "shakes"
  | "beverages";

export type Category = {
  name: string;
  slug: CategorySlug;
  description: string;
  image: string;
};

export type MenuItem = {
  id: string;
  name: string;
  slug: string;
  category: string;
  categorySlug: CategorySlug;
  price: number | "MRP";
  displayPrice: string;
  description: string;
  image: string;
  tag?: string;
  isSignature?: boolean;
  isPopular?: boolean;
};

export const restaurant = {
  name: "Belgian Broast",
  city: "Rampur",
  address:
    "Opposite Khushboo Garden, Jheel Road, Rampur, Thotar, Uttar Pradesh 244901",
  phone: "8868880002",
  whatsapp: "918868880002",
  email: "info@belgianbroast.com",
  hours: "Mon - Sun : 12:30 PM - 11:00 PM",

  seo: {
    title: "Belgian Broast Rampur | Family Restaurant",
    description:
      "Belgian Broast Rampur family restaurant serving broast chicken, burgers, pizza, wraps, fries, combos, shakes and beverages.",
    keywords:
      "Belgian Broast Rampur, family restaurant Rampur, broast chicken Rampur, burgers Rampur, pizza Rampur, best restaurant Rampur",
    siteUrl: "https://belgianbroast.com",
  },

  heroImage: "/restaurant-images/hero-restaurant.jpg",

  categories: [
    {
      name: "Broast Special",
      slug: "broast-special",
      description: "Signature crispy broast chicken, popcorn and chizza.",
      image: "/restaurant-images/broast-chicken.jpg",
    },
    {
      name: "Burgers",
      slug: "burgers",
      description: "Zinger, paneer and herb chilli burgers.",
      image: "/restaurant-images/menu/special-zinger-burger.png",
    },
    {
      name: "Wraps",
      slug: "wraps",
      description: "Fresh wraps with chicken, paneer and veg fillings.",
      image: "/restaurant-images/menu/zinger-wrap.png",
    },
    {
      name: "Pizza",
      slug: "pizza",
      description: "Chicken, paneer, veg and cheese pizzas.",
      image: "/restaurant-images/menu/bbq-chicken-pizza.png",
    },
    {
      name: "Fries",
      slug: "fries",
      description: "Classic, peri peri and loaded fries.",
      image: "/restaurant-images/menu/classic-french-fries.png",
    },
    {
      name: "Combos",
      slug: "combos",
      description: "Value combos for quick meals.",
      image: "/restaurant-images/zinger-combo.jpg",
    },
    {
      name: "Shakes",
      slug: "shakes",
      description: "Creamy strawberry, vanilla, Oreo and chocolate shakes.",
      image: "/restaurant-images/menu/oreo-shake.png",
    },
    {
      name: "Beverages",
      slug: "beverages",
      description: "Coffee, lemonade, mojito and cold drinks.",
      image: "/restaurant-images/menu/virgin-mojito.png",
    },
  ] satisfies Category[],

  menu: [
    {
      id: "classic-chicken-broast",
      name: "Classic Chicken Broast",
      slug: "classic-chicken-broast",
      category: "Broast Special",
      categorySlug: "broast-special",
      price: 249,
      displayPrice: "₹249",
      description: "2pcs Wings + 2pcs legs.",
      image: "/restaurant-images/broast-chicken.jpg",
      tag: "Popular",
      isSignature: true,
      isPopular: true,
    },
    {
      id: "classic-chicken-broast-bucket",
      name: "Classic Chicken Broast Bucket",
      slug: "classic-chicken-broast-bucket",
      category: "Broast Special",
      categorySlug: "broast-special",
      price: 349,
      displayPrice: "₹349",
      description: "2pcs Wings + 2pcs legs + 2pcs Boneless.",
      image: "/restaurant-images/broast-bucket.jpg",
      isPopular: true,
    },
    {
      id: "family-broast-meal-bucket",
      name: "Family Broast Meal Bucket",
      slug: "family-broast-meal-bucket",
      category: "Broast Special",
      categorySlug: "broast-special",
      price: 549,
      displayPrice: "₹549",
      description: "10pcs full Chicken family-size broast meal bucket.",
      image: "/restaurant-images/broast-family-bucket.jpg",
      tag: "Family Pack",
      isSignature: true,
    },
    {
      id: "spicy-chicken-popcorn",
      name: "Spicy Chicken Popcorn",
      slug: "spicy-chicken-popcorn",
      category: "Broast Special",
      categorySlug: "broast-special",
      price: 149,
      displayPrice: "₹149",
      description: "8-10pcs Boneless chicken.",
      image: "/restaurant-images/chicken-popcorn.jpg",
    },
    {
      id: "special-loaded-chicken-popcorn",
      name: "Special Loaded Chicken Popcorn",
      slug: "special-loaded-chicken-popcorn",
      category: "Broast Special",
      categorySlug: "broast-special",
      price: 199,
      displayPrice: "₹199",
      description: "Tender juicy chicken bites, layered with cheese and sauces.",
      image: "/restaurant-images/menu/special-loaded-chicken-popcorn.png",
      tag: "Special",
      isSignature: true,
    },
    {
      id: "special-tandoori-chicken-chizza",
      name: "Special Tandoori Chicken Chizza",
      slug: "special-tandoori-chicken-chizza",
      category: "Broast Special",
      categorySlug: "broast-special",
      price: 249,
      displayPrice: "₹249",
      description:
        "Crispy chicken base topped with rich cheese, flavorful sauces and fresh toppings.",
      image: "/restaurant-images/menu/special-tandoori-chicken-chizza.png",
      tag: "Special",
      isSignature: true,
    },

    {
      id: "special-zinger-burger",
      name: "Special Zinger Burger",
      slug: "special-zinger-burger",
      category: "Burgers",
      categorySlug: "burgers",
      price: 119,
      displayPrice: "₹119",
      description: "Crispy zinger burger with special sauce.",
      image: "/restaurant-images/menu/special-zinger-burger.png",
      tag: "Best Seller",
      isPopular: true,
    },
    {
      id: "spicy-zinger-burger",
      name: "Spicy Zinger Burger",
      slug: "spicy-zinger-burger",
      category: "Burgers",
      categorySlug: "burgers",
      price: 119,
      displayPrice: "₹119",
      description: "Spicy crispy chicken burger with fresh veggies.",
      image: "/restaurant-images/menu/spicy-zinger-burger.png",
    },
    {
      id: "mega-zinger-burger",
      name: "Mega Zinger Burger",
      slug: "mega-zinger-burger",
      category: "Burgers",
      categorySlug: "burgers",
      price: 149,
      displayPrice: "₹149",
      description: "Large zinger burger with extra crispy filling.",
      image: "/restaurant-images/menu/mega-zinger-burger.png",
      isPopular: true,
    },
    {
      id: "zinger-burger-duo",
      name: "Zinger Burger Duo",
      slug: "zinger-burger-duo",
      category: "Burgers",
      categorySlug: "burgers",
      price: 219,
      displayPrice: "₹219",
      description: "Two zinger burgers for sharing.",
      image: "/restaurant-images/menu/zinger-burger-duo.png",
      tag: "Duo",
    },
    {
      id: "herb-chilli-burger",
      name: "Herb Chilli Burger",
      slug: "herb-chilli-burger",
      category: "Burgers",
      categorySlug: "burgers",
      price: 69,
      displayPrice: "₹69",
      description: "Veg herb chilli burger with fresh filling.",
      image: "/restaurant-images/menu/herb-chilli-burger.png",
    },
    {
      id: "herb-chilli-burger-duo",
      name: "Herb Chilli Burger Duo",
      slug: "herb-chilli-burger-duo",
      category: "Burgers",
      categorySlug: "burgers",
      price: 119,
      displayPrice: "₹119",
      description: "Two herb chilli burgers for sharing.",
      image: "/restaurant-images/menu/herb-chilli-burger-duo.png",
    },
    {
      id: "tangy-paneer-burger",
      name: "Tangy Paneer Burger",
      slug: "tangy-paneer-burger",
      category: "Burgers",
      categorySlug: "burgers",
      price: 119,
      displayPrice: "₹119",
      description: "Paneer burger with tangy sauce and fresh veggies.",
      image: "/restaurant-images/menu/tangy-paneer-burger.png",
    },

    {
      id: "zinger-wrap",
      name: "Zinger Wrap",
      slug: "zinger-wrap",
      category: "Wraps",
      categorySlug: "wraps",
      price: 99,
      displayPrice: "₹99",
      description: "Crispy zinger wrap with fresh veggies.",
      image: "/restaurant-images/menu/zinger-wrap.png",
    },
    {
      id: "chicken-tikka-wrap",
      name: "Chicken Tikka Wrap",
      slug: "chicken-tikka-wrap",
      category: "Wraps",
      categorySlug: "wraps",
      price: 99,
      displayPrice: "₹99",
      description: "Chicken tikka wrap with creamy sauce.",
      image: "/restaurant-images/chicken-tikka-wrap.jpg",
      isPopular: true,
    },
    {
      id: "paneer-wrap",
      name: "Paneer Wrap",
      slug: "paneer-wrap",
      category: "Wraps",
      categorySlug: "wraps",
      price: 99,
      displayPrice: "₹99",
      description: "Paneer wrap with fresh filling.",
      image: "/restaurant-images/paneer-wrap.jpg",
    },
    {
      id: "mix-veg-wrap",
      name: "Mix Veg Wrap",
      slug: "mix-veg-wrap",
      category: "Wraps",
      categorySlug: "wraps",
      price: 79,
      displayPrice: "₹79",
      description: "Mixed vegetable wrap with special sauce.",
      image: "/restaurant-images/mix-veg-wrap.jpg",
    },

    {
      id: "bbq-chicken-pizza",
      name: "BBQ Chicken Pizza",
      slug: "bbq-chicken-pizza",
      category: "Pizza",
      categorySlug: "pizza",
      price: 259,
      displayPrice: "₹259",
      description: "Smoky BBQ chicken pizza with cheese.",
      image: "/restaurant-images/menu/bbq-chicken-pizza.png",
      tag: "Popular",
      isPopular: true,
    },
    {
      id: "hot-spicy-chicken-pizza",
      name: "Hot & Spicy Chicken Pizza",
      slug: "hot-spicy-chicken-pizza",
      category: "Pizza",
      categorySlug: "pizza",
      price: 259,
      displayPrice: "₹259",
      description: "Spicy chicken pizza with bold flavours.",
      image: "/restaurant-images/menu/hot-spicy-chicken-pizza.png",
    },
    {
      id: "tandoori-chicken-pizza",
      name: "Tandoori Chicken Pizza",
      slug: "tandoori-chicken-pizza",
      category: "Pizza",
      categorySlug: "pizza",
      price: 269,
      displayPrice: "₹269",
      description: "Tandoori chicken pizza with rich cheese and sauces.",
      image: "/restaurant-images/menu/tandoori-chicken-pizza.png",
    },
    {
      id: "chicken-tikka-pizza",
      name: "Chicken Tikka Pizza",
      slug: "chicken-tikka-pizza",
      category: "Pizza",
      categorySlug: "pizza",
      price: 269,
      displayPrice: "₹269",
      description: "Chicken tikka pizza with flavorful toppings.",
      image: "/restaurant-images/bbq-chicken-pizza.jpg",
    },
    {
      id: "margherita-pizza",
      name: "Margherita Pizza",
      slug: "margherita-pizza",
      category: "Pizza",
      categorySlug: "pizza",
      price: 199,
      displayPrice: "₹199",
      description: "Classic cheese pizza with tomato base.",
      image: "/restaurant-images/menu/margherita-pizza.png",
    },
    {
      id: "hot-spicy-veg-pizza",
      name: "Hot & Spicy Veg Pizza",
      slug: "hot-spicy-veg-pizza",
      category: "Pizza",
      categorySlug: "pizza",
      price: 249,
      displayPrice: "₹249",
      description: "Spicy veg pizza with cheesy toppings.",
      image: "/restaurant-images/menu/hot-spicy-veg-pizza.png",
    },
    {
      id: "paneer-tikka-pizza",
      name: "Paneer Tikka Pizza",
      slug: "paneer-tikka-pizza",
      category: "Pizza",
      categorySlug: "pizza",
      price: 249,
      displayPrice: "₹249",
      description: "Paneer tikka pizza with cheesy toppings.",
      image: "/restaurant-images/menu/paneer-tikka-pizza.png",
    },
    {
      id: "farmhouse-delight-pizza",
      name: "Farmhouse Delight Pizza",
      slug: "farmhouse-delight-pizza",
      category: "Pizza",
      categorySlug: "pizza",
      price: 249,
      displayPrice: "₹249",
      description: "Veg farmhouse pizza with fresh toppings.",
      image: "/restaurant-images/menu/farmhouse-delight-pizza.png",
    },

    {
      id: "classic-french-fries",
      name: "Classic French Fries",
      slug: "classic-french-fries",
      category: "Fries",
      categorySlug: "fries",
      price: 79,
      displayPrice: "₹79",
      description: "Golden crispy salted fries.",
      image: "/restaurant-images/menu/classic-french-fries.png",
    },
    {
      id: "peri-peri-fries",
      name: "Peri Peri Fries",
      slug: "peri-peri-fries",
      category: "Fries",
      categorySlug: "fries",
      price: 89,
      displayPrice: "₹89",
      description: "Crispy fries with peri-peri seasoning.",
      image: "/restaurant-images/peri-peri-fries.jpg",
    },
    {
      id: "loaded-fries",
      name: "Loaded Fries",
      slug: "loaded-fries",
      category: "Fries",
      categorySlug: "fries",
      price: 129,
      displayPrice: "₹129",
      description: "Fries loaded with cheese and sauces.",
      image: "/restaurant-images/loaded-fries.jpg",
      isPopular: true,
    },

    {
      id: "zinger-combo",
      name: "Zinger Combo",
      slug: "zinger-combo",
      category: "Combos",
      categorySlug: "combos",
      price: 199,
      displayPrice: "₹199",
      description: "Zinger burger with fries and soft drink.",
      image: "/restaurant-images/zinger-combo.jpg",
      tag: "Combo",
      isPopular: true,
    },
    {
      id: "broast-combo",
      name: "Broast Combo",
      slug: "broast-combo",
      category: "Combos",
      categorySlug: "combos",
      price: 339,
      displayPrice: "₹339",
      description: "Chicken broast with fries and soft drink.",
      image: "/restaurant-images/broast-combo.jpg",
      isSignature: true,
    },

    {
      id: "strawberry-shake",
      name: "Strawberry Shake",
      slug: "strawberry-shake",
      category: "Shakes",
      categorySlug: "shakes",
      price: 119,
      displayPrice: "₹119",
      description: "Creamy strawberry shake.",
      image: "/restaurant-images/menu/strawberry-shake.png",
    },
    {
      id: "vanilla-shake",
      name: "Vanilla Shake",
      slug: "vanilla-shake",
      category: "Shakes",
      categorySlug: "shakes",
      price: 119,
      displayPrice: "₹119",
      description: "Creamy vanilla shake.",
      image: "/restaurant-images/menu/vanilla-shake.png",
    },
    {
      id: "oreo-shake",
      name: "Oreo Shake",
      slug: "oreo-shake",
      category: "Shakes",
      categorySlug: "shakes",
      price: 139,
      displayPrice: "₹139",
      description: "Creamy Oreo shake with chocolate crunch.",
      image: "/restaurant-images/menu/oreo-shake.png",
      isPopular: true,
    },
    {
      id: "chocolate-shake",
      name: "Chocolate Shake",
      slug: "chocolate-shake",
      category: "Shakes",
      categorySlug: "shakes",
      price: 129,
      displayPrice: "₹129",
      description: "Creamy chocolate shake.",
      image: "/restaurant-images/menu/chocolate-shake.png",
    },

    {
      id: "cold-coffee",
      name: "Cold Coffee",
      slug: "cold-coffee",
      category: "Beverages",
      categorySlug: "beverages",
      price: 99,
      displayPrice: "₹99",
      description: "Chilled creamy cold coffee.",
      image: "/restaurant-images/menu/cold-coffee.png",
      isPopular: true,
    },
    {
      id: "iced-lemonade",
      name: "Iced Lemonade",
      slug: "iced-lemonade",
      category: "Beverages",
      categorySlug: "beverages",
      price: 79,
      displayPrice: "₹79",
      description: "Refreshing iced lemonade.",
      image: "/restaurant-images/menu/iced-lemonade.png",
    },
    {
      id: "virgin-mojito",
      name: "Virgin Mojito",
      slug: "virgin-mojito",
      category: "Beverages",
      categorySlug: "beverages",
      price: 79,
      displayPrice: "₹79",
      description: "Refreshing mint mojito.",
      image: "/restaurant-images/menu/virgin-mojito.png",
    },
    {
      id: "regular-filter-coffee",
      name: "Regular Filter Coffee",
      slug: "regular-filter-coffee",
      category: "Beverages",
      categorySlug: "beverages",
      price: 59,
      displayPrice: "₹59",
      description: "Classic regular filter coffee.",
      image: "/restaurant-images/menu/regular-filter-coffee.png",
    },
    {
      id: "hand-beaten-coffee",
      name: "Hand Beaten Coffee",
      slug: "hand-beaten-coffee",
      category: "Beverages",
      categorySlug: "beverages",
      price: 99,
      displayPrice: "₹99",
      description: "Rich hand beaten coffee.",
      image: "/restaurant-images/menu/hand-beaten-coffee.png",
    },
    {
      id: "black-coffee",
      name: "Black Coffee",
      slug: "black-coffee",
      category: "Beverages",
      categorySlug: "beverages",
      price: 59,
      displayPrice: "₹59",
      description: "Classic black coffee.",
      image: "/restaurant-images/menu/black-coffee.png",
    },
    {
      id: "cold-drinks",
      name: "Cold Drinks",
      slug: "cold-drinks",
      category: "Beverages",
      categorySlug: "beverages",
      price: "MRP",
      displayPrice: "MRP",
      description: "Cold drinks available at MRP.",
      image: "/restaurant-images/menu/cold-drinks.png",
    },
  ] satisfies MenuItem[],

  gallery: [
    "/restaurant-images/gallery/gallery-1.jpg",
    "/restaurant-images/gallery/gallery-2.jpg",
    "/restaurant-images/gallery/gallery-3.jpg",
    "/restaurant-images/gallery/gallery-4.jpg",
    "/restaurant-images/gallery/gallery-5.jpg",
    "/restaurant-images/gallery/gallery-6.jpg",
    "/restaurant-images/gallery/gallery-7.jpg",
    "/restaurant-images/gallery/gallery-8.jpg",
    "/restaurant-images/gallery/gallery-9.jpg",
    "/restaurant-images/gallery/gallery-10.jpg",
  ],

  reviews: [
    {
      name: "Amaan Khan",
      text: "Amazing taste and fresh food. Broast chicken was crispy and delicious.",
    },
    {
      name: "Sara Ali",
      text: "Best place in Rampur for burgers, pizza and family dinner.",
    },
    {
      name: "Faizan Qureshi",
      text: "Good ambience, quick service and tasty food.",
    },
  ],

  mapEmbed:
    "https://maps.google.com/maps?q=Belgian%20Broast%20Opposite%20Khushboo%20Garden%20Jheel%20Road%20Rampur%20Uttar%20Pradesh%20244901&t=&z=16&ie=UTF8&iwloc=&output=embed",

  socials: {
    instagram: "https://www.instagram.com/belgianbroastrampur/",
    facebook:
      "https://www.facebook.com/p/Belgian-Broast-Restaurant-61580565897770/",
    youtube: "https://www.youtube.com/channel/UC4g3bMVZRBA4KdgfYiqrn2Q",
  },
};

export const getCategoryBySlug = (slug: string) =>
  restaurant.categories.find((category) => category.slug === slug);

export const getMenuByCategorySlug = (slug: string) =>
  restaurant.menu.filter((item) => item.categorySlug === slug);

export const getMenuItemBySlug = (slug: string) =>
  restaurant.menu.find((item) => item.slug === slug);

export const signatureItems = restaurant.menu.filter((item) => item.isSignature);

export const popularItems = restaurant.menu.filter((item) => item.isPopular);